#!/usr/bin/env python3
"""Apply irons template to remaining pages."""
import re, os

DIST = r'/mnt/c/Users/mikae/workspace/golf-kenya/dist/products'

SKUS = ['mzj', 'mzp', 'pgbt', 'pgg', 'pggg', 'pggs', 'pgi', 'pxxg', 'tmqi', 'tms', 'tmsm', 'ttt']

# Read the template to use as a structural reference
# We'll build pages from scratch

BRAND_SPECS = {
    "mzj": {"style": "Game Improvement", "hcp": "10-25+", "forgiveness": "High", "trajectory": "High", "workability": "Low", "face": "Forged Chromoly (4120)"},
    "mzp": {"style": "Players Distance", "hcp": "3-15", "forgiveness": "Medium", "trajectory": "Mid", "workability": "High", "face": "Forged 1025E Carbon Steel"},
    "pgbt": {"style": "Players", "hcp": "0-10", "forgiveness": "Low-Medium", "trajectory": "Mid", "workability": "High", "face": "Forged 8620 Carbon Steel"},
    "pgg": {"style": "Game Improvement", "hcp": "10-25+", "forgiveness": "Very High", "trajectory": "High", "workability": "Low", "face": "Stainless Steel (17-4)"},
    "pggg": {"style": "Game Improvement", "hcp": "10-25+", "forgiveness": "Very High", "trajectory": "High", "workability": "Low", "face": "Stainless Steel (17-4)"},
    "pggs": {"style": "Game Improvement", "hcp": "10-25+", "forgiveness": "Very High", "trajectory": "High", "workability": "Low", "face": "Stainless Steel (17-4)"},
    "pgi": {"style": "Players Distance", "hcp": "5-18", "forgiveness": "High", "trajectory": "Mid-High", "workability": "Medium", "face": "Forged 455 Steel"},
    "pxxg": {"style": "Players Distance", "hcp": "3-20", "forgiveness": "High", "trajectory": "Mid-High", "workability": "Medium", "face": "Forged HT1770 Steel"},
    "tmqi": {"style": "Game Improvement", "hcp": "10-25+", "forgiveness": "High", "trajectory": "High", "workability": "Medium", "face": "Forged 450 Steel"},
    "tms": {"style": "Game Improvement", "hcp": "10-25+", "forgiveness": "Very High", "trajectory": "High", "workability": "Low", "face": "Forged 450 Steel"},
    "tmsm": {"style": "Game Improvement", "hcp": "10-25+", "forgiveness": "Very High", "trajectory": "High", "workability": "Low", "face": "Forged 450 Steel"},
    "ttt": {"style": "Players Distance", "hcp": "5-20", "forgiveness": "High", "trajectory": "Mid-High", "workability": "Medium", "face": "Forged 8620 Carbon Steel"},
}

def extract(fpath):
    with open(fpath, encoding='utf-8') as f:
        c = f.read()
    m = re.search(r'<title>([^<]+)', c)
    title = m.group(1).replace(' - KARIBU', '') if m else ''
    m = re.search(r'<meta name="description" content="([^"]+)', c)
    meta = m.group(1) if m else title
    m = re.search(r'(KES\s*[\d,]+)', c)
    price = m.group(1) if m else 'KES 0'
    images = re.findall(r'/images/products/([^"\'<>\s]+)', c)
    seen = set()
    uniq = []
    for img in images:
        if img not in seen:
            seen.add(img)
            uniq.append(img)
    main = uniq[0] if uniq else 'placeholder.jpg'
    thumbs = uniq[:4]
    while len(thumbs) < 4:
        thumbs.append(thumbs[0])
    dm = re.search(r'<p[^>]*class="[^"]*desc[^"]*"[^>]*>(.*?)</p>', c, re.DOTALL)
    desc = re.sub(r'<[^>]+>', '', dm.group(1)).strip() if dm else meta
    return title, meta, price, main, thumbs, desc

def write_page(sku):
    fpath = os.path.join(DIST, f'gk-ir-{sku}.html')
    title, meta, price, main, thumbs, desc = extract(fpath)
    sku_code = f'GK-IR-{sku.upper()}'
    price_num = re.sub(r'[^\d]', '', price)
    wa = f'I%20am%20interested%20in%20the%20{title.replace(chr(32), "%20")}%20({sku_code})'
    bs = BRAND_SPECS.get(sku, {})
    
    # Build loft table
    loft_rows = [
        ['4 Iron','19.0','61.5','5.8mm','2','39.125','D1'],
        ['5 Iron','21.5','62.0','5.2mm','3','38.50','D1'],
        ['6 Iron','25.0','62.5','4.7mm','5','37.88','D1'],
        ['7 Iron','28.5','63.0','4.2mm','5','37.25','D1'],
        ['8 Iron','32.5','63.5','3.5mm','6.5','36.75','D1'],
        ['9 Iron','38.0','64.0','3.0mm','7','36.25','D1'],
        ['PW','43.5','64.5','2.6mm','7.5','35.75','D1'],
        ['AW','49.0','64.5','2.0mm','7.5','35.50','D1'],
        ['SW','54.0','64.5','1.5mm','9','35.25','D3'],
        ['LW','59.0','64.5','1.5mm','9','35.00','D3'],
    ]
    
    lines = []
    a = lines.append
    
    a('<!DOCTYPE html>')
    a('<html lang="en">')
    a('<head>')
    a('    <meta charset="UTF-8">')
    a('    <meta name="viewport" content="width=device-width, initial-scale=1.0">')
    a(f'    <title>{title} - KARIBU</title>')
    a(f'    <meta name="description" content="{meta}">')
    a('    <link rel="preconnect" href="https://fonts.googleapis.com">')
    a('    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&family=Playfair+Display:wght@400;500;600;700&display=swap" rel="stylesheet">')
    a('    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">')
    a('    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">')
    a('    <link rel="stylesheet" href="/styles.css">')
    a('    <style>')
    a('.product-detail { padding: 60px 0; background: #f8f5ee; min-height: calc(100vh - 400px); }')
    a('.product-detail-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 50px; align-items: start; max-width:1400px; margin:0 auto; padding:0 40px; }')
    a('.product-detail-image { background: transparent; border-radius: 0; overflow: visible; box-shadow: none; filter: drop-shadow(0 15px 40px rgba(0,0,0,0.15)); position:relative; }')
    a('.product-detail-image img { width: 100%; height: auto; display: block; border-radius: 12px; }')
    a('.product-detail-info { padding-top: 10px; }')
    a('.product-detail-badge { display: inline-block; background: #1f5132; color: #c9a961; padding: 4px 14px; border-radius: 20px; font-size: 12px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 15px; }')
    a('.product-detail-title { font-family: \'Playfair Display\', serif; font-size: 32px; color: #1a1a1a; margin-bottom: 10px; font-weight: 700; }')
    a('.product-detail-sku { font-size: 14px; color: #888; margin-bottom: 15px; }')
    a('.product-detail-price { font-size: 36px; font-weight: 800; color: #1f5132; margin: 20px 0; }')
    a('.product-detail-desc { color: #555; line-height: 1.8; margin-bottom: 30px; font-size: 15px; }')
    a('.pimage-main { width:100%; margin-bottom:12px; }')
    a('.pimage-main img { width:100% !important; height:auto !important; display:block !important; }')
    a('.pimage-thumbs { display:flex !important; gap:8px; margin-top:0; flex-wrap:wrap; }')
    a('.pthumb { width:70px !important; height:70px !important; object-fit:cover; border-radius:8px; border:2px solid #e0d8c8; cursor:pointer; transition:all 0.2s; }')
    a('.pthumb:hover { border-color:#c9a961; transform:scale(1.05); }')
    a('.configurator { background:#f8f5ee; border-radius:16px; padding:20px; margin:20px 0; border:1px solid #e8e0d0; }')
    a('.config-title { font-size:16px; font-weight:700; color:#1f5132; margin-bottom:16px; font-family:\'Montserrat\',sans-serif; }')
    a('.config-row { display:flex; gap:12px; margin-bottom:12px; }')
    a('.config-field { flex:1; min-width:0; }')
    a('.config-field label { display:block; font-size:11px; font-weight:600; color:#888; text-transform:uppercase; letter-spacing:0.5px; margin-bottom:5px; }')
    a('.config-field select { width:100%; padding:10px 12px; border:2px solid #d0c8b8; border-radius:10px; background:#fff; color:#333; font-size:13px; font-weight:500; cursor:pointer; transition:all 0.2s; appearance:auto; }')
    a('.config-field select:focus { border-color:#1f5132; outline:none; }')
    a('.config-summary { background:#fff; border-radius:10px; padding:12px 16px; display:flex; align-items:center; gap:10px; font-size:13px; font-weight:500; color:#1f5132; border:1px solid #e8e0d0; margin-top:12px; }')
    a('@media (max-width:500px) { .config-row { flex-direction:column; gap:10px; } }')
    a('.product-detail-actions { display: flex; gap: 15px; flex-wrap: wrap; margin: 20px 0; }')
    a('.btn-detail-inquire { display: inline-flex; align-items: center; gap: 10px; background: #25D366; color: #fff; padding: 15px 35px; border-radius: 50px; font-size: 16px; font-weight: 600; border: none; cursor: pointer; transition: all 0.3s; text-decoration: none; }')
    a('.btn-detail-inquire:hover { background: #1da851; transform: translateY(-2px); }')
    a('.btn-detail-cart { display: inline-flex; align-items: center; gap: 10px; background: #1f5132; color: #fff; padding: 15px 35px; border-radius: 50px; font-size: 16px; font-weight: 600; border: none; cursor: pointer; transition: all 0.3s; text-decoration: none; }')
    a('.btn-detail-cart:hover { background: #163d26; transform: translateY(-2px); }')
    a('.product-specs { margin: 20px 0; padding: 20px; background: #fff; border-radius: 16px; border: 1px solid #e8e0d0; }')
    a('.specs-title { font-family: \'Playfair Display\', serif; font-size: 20px; font-weight: 700; color: #1f5132; margin-bottom: 16px; }')
    a('.specs-title::after { content:""; display:block; width:50px; height:3px; background:#c9a961; margin-top:6px; }')
    a('.specs-list { list-style: none; padding: 0; margin: 0; }')
    a('.specs-list li { display: flex; padding: 10px 0; border-bottom: 1px solid #f0e8d8; font-size: 14px; }')
    a('.specs-list li:last-child { border-bottom: none; }')
    a('.spec-label { width: 45%; font-weight: 600; color: #1a1a1a; flex-shrink: 0; }')
    a('.spec-value { width: 55%; color: #555; }')
    a('.loft-table-wrapper { margin: 0; overflow-x: auto; }')
    a('.loft-table { width: 100%; border-collapse: collapse; border-radius: 12px; overflow: hidden; font-size: 13px; }')
    a('.loft-table thead { background: #1f5132; }')
    a('.loft-table thead th { color: #c9a961; padding: 10px 12px; text-align: left; font-weight: 600; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }')
    a('.loft-table tbody tr:nth-child(odd) { background: #fff; }')
    a('.loft-table tbody tr:nth-child(even) { background: #e8f0ea; }')
    a('.loft-table tbody td { padding: 8px 12px; color: #333; border-bottom: 1px solid #d0d8d0; }')
    a('.pimage-specs { margin-top:24px; padding:20px; background:#f8f5ee; border-radius:16px; border:1px solid #e8e0d0; }')
    a('.pimage-specs .specs-title { font-size:16px; margin-bottom:12px; }')
    a('.pimage-specs .loft-table { font-size:12px; }')
    a('.pimage-specs .loft-table thead th { padding:7px 8px; font-size:10px; }')
    a('.pimage-specs .loft-table tbody td { padding:5px 8px; }')
    a('.back-to-shop { text-align: left; margin-bottom: 16px; max-width:1400px; margin-left: auto; margin-right: auto; padding:0 40px; }')
    a('.back-to-shop a { color: #1f5132; text-decoration: none; font-weight: 500; font-size: 15px; }')
    a('.back-to-shop a:hover { color: #c9a961; }')
    a('@media (max-width:768px) { .product-detail-grid { grid-template-columns: 1fr; gap: 30px; } .product-detail-title { font-size: 24px; } .product-detail-price { font-size: 28px; } .back-to-shop { padding:0 20px; } }')
    a('.lightbox-overlay { display:none; position:fixed; top:0; left:0; width:100%; height:100%; background:rgba(0,0,0,0.92); z-index:9999; justify-content:center; align-items:center; cursor:pointer; }')
    a('.lightbox-overlay.active { display:flex; }')
    a('.lightbox-overlay img { max-width:90vw; max-height:90vh; object-fit:contain; border-radius:8px; }')
    a('.lightbox-close { position:absolute; top:20px; right:30px; color:#fff; font-size:40px; cursor:pointer; font-weight:300; transition:all 0.2s; line-height:1; }')
    a('.lightbox-close:hover { color:#c9a961; transform:scale(1.1); }')
    a('.lightbox-prev, .lightbox-next { position:absolute; top:50%; transform:translateY(-50%); color:#fff; font-size:50px; cursor:pointer; font-weight:300; padding:20px; transition:all 0.2s; user-select:none; }')
    a('.lightbox-prev { left:20px; }')
    a('.lightbox-next { right:20px; }')
    a('.lightbox-prev:hover, .lightbox-next:hover { color:#c9a961; }')
    a('    </style>')
    a('</head>')
    a('<body>')
    a('    <div class="lightbox-overlay" id="lightbox" onclick="closeLightbox(event)">')
    a('        <span class="lightbox-close" onclick="closeLightbox(event)">&times;</span>')
    a('        <span class="lightbox-prev" onclick="prevImage(event)">&#8249;</span>')
    a('        <img id="lightboxImg" src="" alt="Product Image">')
    a('        <span class="lightbox-next" onclick="nextImage(event)">&#8250;</span>')
    a('    </div>')
    a('    <nav class="navbar">')
    a('        <div class="nav-container">')
    a('            <a href="/" class="nav-logo">')
    a('                <img src="/images/karibu-logo-small.png" alt="Karibu" style="height:32px;width:32px;border-radius:50%;">')
    a('                <span class="logo-text">KARIBU</span>')
    a('            </a>')
    a('            <ul class="nav-menu">')
    a('                <li><a href="/" class="nav-link">Home</a></li>')
    a('                <li><a href="/categories/" class="nav-link">Categories</a></li>')
    a('                <li><a href="/#products" class="nav-link">Shop</a></li>')
    a('                <li><a href="/about.html" class="nav-link">About</a></li>')
    a('                <li><a href="/#contact" class="nav-link">Contact</a></li>')
    a('            </ul>')
    a('            <div class="nav-actions">')
    a('                <a href="https://wa.me/8613262570197" class="btn-nav-cta" target="_blank">')
    a('                    <i class="fab fa-whatsapp"></i> Chat')
    a('                </a>')
    a('            </div>')
    a('            <button class="nav-toggle" id="navToggle">')
    a('                <span></span><span></span><span></span>')
    a('            </button>')
    a('        </div>')
    a('    </nav>')
    a('')
    a('    <div class="back-to-shop">')
    a('        <a href="/categories/golf_irons.html"><i class="fas fa-arrow-left"></i> Back to Irons</a>')
    a('    </div>')
    a('')
    a('    <section class="product-detail">')
    a('        <div class="product-detail-grid">')
    a('            <!-- LEFT COLUMN: Images + Loft Specs -->')
    a('            <div class="product-detail-image" data-aos="fade-right">')
    a(f'                <div class="pimage-main"><img id="pmain" src="/images/products/{main}" alt="{title}"></div>')
    a('                <div class="pimage-thumbs">')
    labels = ['Angle', 'Sole', 'Face', 'Back']
    for i, t in enumerate(thumbs[:4]):
        a(f'                    <img class="pthumb" src="/images/products/{t}" alt="{labels[i]}" onclick="document.getElementById(\'pmain\').src=this.src">')
    a('                </div>')
    a('                <div class="pimage-specs">')
    a('                    <h3 class="specs-title">Loft and Length Specs</h3>')
    a('                    <table class="loft-table">')
    a('                        <thead>')
    a('                            <tr><th>Club</th><th>Loft</th><th>Lie</th><th>Offset</th><th>Bounce</th><th>Length</th><th>Swing Wt</th></tr>')
    a('                        </thead>')
    a('                        <tbody>')
    for row in loft_rows:
        a(f'                            <tr><td>{row[0]}</td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td>{row[4]}</td><td>{row[5]}</td><td>{row[6]}</td></tr>')
    a('                        </tbody>')
    a('                    </table>')
    a('                </div>')
    a('            </div>')
    a('')
    a('            <!-- RIGHT COLUMN: Product Info -->')
    a('            <div class="product-detail-info">')
    a('                <span class="product-detail-badge">Irons</span>')
    a(f'                <h1 class="product-detail-title">{title}</h1>')
    a(f'                <div class="product-detail-sku">SKU: {sku_code}</div>')
    a(f'                <div class="product-detail-price">{price}</div>')
    a('                <div class="product-detail-desc">')
    a(f'                    {desc}')
    a('                </div>')
    a('')
    a('                <div class="configurator">')
    a('                    <h3 class="config-title">Customize Your Set</h3>')
    a('                    <div class="config-row">')
    a('                        <div class="config-field">')
    a('                            <label>Set Composition</label>')
    a('                            <select id="selSet" onchange="updateConfig()">')
    a('                                <option value="4-PW+AW (8 Irons)" selected>4-PW+AW (8 Irons)</option>')
    a('                                <option value="4-PW (7 Irons)">4-PW (7 Irons)</option>')
    a('                                <option value="5-PW+AW+SW (8 Irons)">5-PW+AW+SW (8 Irons)</option>')
    a('                                <option value="5-PW+SW (7 Irons)">5-PW+SW (7 Irons)</option>')
    a('                                <option value="5-PW+AW (7 Irons)">5-PW+AW (7 Irons)</option>')
    a('                                <option value="5-PW (6 Irons)">5-PW (6 Irons)</option>')
    a('                            </select>')
    a('                        </div>')
    a('                        <div class="config-field">')
    a('                            <label>Shaft Type</label>')
    a('                            <select id="selShaft" onchange="updateConfig()">')
    a('                                <option value="steel" selected>Steel - KBS Max 85 MT</option>')
    a('                                <option value="graphite">Graphite - Fujikura Ventus TR Blue</option>')
    a('                            </select>')
    a('                        </div>')
    a('                    </div>')
    a('                    <div class="config-row">')
    a('                        <div class="config-field">')
    a('                            <label>Flex</label>')
    a('                            <select id="selFlex" onchange="updateConfig()">')
    a('                                <option value="Stiff (S)" selected>Stiff (S)</option>')
    a('                                <option value="Regular (R)">Regular (R)</option>')
    a('                                <option value="Senior (A)">Senior (A)</option>')
    a('                            </select>')
    a('                        </div>')
    a('                        <div class="config-field">')
    a('                            <label>Hand</label>')
    a('                            <select id="selHand" onchange="updateConfig()">')
    a('                                <option value="Right Hand" selected>Right Hand</option>')
    a('                            </select>')
    a('                        </div>')
    a('                    </div>')
    a('                    <div class="config-summary" id="configSummary">')
    a('                        <i class="fas fa-check-circle" style="color:#c9a961;"></i>')
    a('                        <span>4-PW+AW (8 Irons) - KBS Max 85 MT - Stiff (S) - Right Hand</span>')
    a('                    </div>')
    a('                </div>')
    a('')
    a('                <div class="product-detail-actions">')
    a(f'                    <a href="javascript:void(0)" class="btn-detail-cart" onclick="addToCart(\'{title}\', {price_num}, \'/images/products/{main}\', document.getElementById(\'configSummary\').querySelector(\'span\').textContent)">')
    a('                        <i class="fas fa-shopping-cart"></i> Add to Cart')
    a('                    </a>')
    a(f'                    <a href="https://wa.me/8613262570197?text={wa}" target="_blank" class="btn-detail-inquire">')
    a('                        <i class="fab fa-whatsapp"></i> Inquire via WhatsApp')
    a('                    </a>')
    a('                </div>')
    a('')
    a('                <div class="product-specs">')
    a('                    <h3 class="specs-title">Product Specifications</h3>')
    a('                    <ul class="specs-list">')
    a(f'                        <li><span class="spec-label">Model</span><span class="spec-value">{title}</span></li>')
    a(f'                        <li><span class="spec-label">Style</span><span class="spec-value">{bs["style"]} - HCP {bs["hcp"]}</span></li>')
    a(f'                        <li><span class="spec-label">Forgiveness</span><span class="spec-value">{bs["forgiveness"]}</span></li>')
    a(f'                        <li><span class="spec-label">Trajectory</span><span class="spec-value">{bs["trajectory"]}</span></li>')
    a(f'                        <li><span class="spec-label">Workability</span><span class="spec-value">{bs["workability"]}</span></li>')
    a(f'                        <li><span class="spec-label">Face Material</span><span class="spec-value">{bs["face"]}</span></li>')
    a('                        <li><span class="spec-label">Set</span><span class="spec-value">4-PW+AW (8 Irons)</span></li>')
    a('                        <li><span class="spec-label">Grip</span><span class="spec-value">Lamkin Crossline 360</span></li>')
    a('                        <li><span class="spec-label">Shaft Steel</span><span class="spec-value">KBS Max 85 MT (S/R)</span></li>')
    a('                        <li><span class="spec-label">Shaft Graphite</span><span class="spec-value">Fujikura Ventus TR Blue (S/R/A)</span></li>')
    a('                        <li><span class="spec-label">Status</span><span class="spec-value">In Stock</span></li>')
    a('                    </ul>')
    a('                </div>')
    a('            </div>')
    a('        </div>')
    a('    </section>')
    a('')
    a('    <footer class="footer">')
    a('        <div class="container">')
    a('            <div class="footer-grid">')
    a('                <div class="footer-brand">')
    a('                    <a href="/" class="footer-logo">')
    a('                        <img src="/images/karibu-logo-small.png" alt="Karibu" style="height:24px;width:24px;border-radius:50%;vertical-align:middle;margin-right:8px;">')
    a('                        <span class="logo-text">KARIBU</span>')
    a('                    </a>')
    a('                    <p>Premium golf equipment and lifestyle products for the discerning golfer in Kenya.</p>')
    a('                    <div class="social-links">')
    a('                        <a href="#"><i class="fab fa-instagram"></i></a>')
    a('                        <a href="#"><i class="fab fa-facebook"></i></a>')
    a('                        <a href="#"><i class="fab fa-twitter"></i></a>')
    a('                    </div>')
    a('                </div>')
    a('                <div class="footer-links">')
    a('                    <h4>Quick Links</h4>')
    a('                    <ul>')
    a('                        <li><a href="/#products">Shop</a></li>')
    a('                        <li><a href="/about.html">About Us</a></li>')
    a('                        <li><a href="/#brands">Brands</a></li>')
    a('                        <li><a href="/#contact">Contact</a></li>')
    a('                    </ul>')
    a('                </div>')
    a('                <div class="footer-links">')
    a('                    <h4>Brands</h4>')
    a('                    <ul>')
    a('                        <li><a href="#">TaylorMade</a></li>')
    a('                        <li><a href="#">Callaway</a></li>')
    a('                        <li><a href="#">J.Lindeberg</a></li>')
    a('                        <li><a href="#">Titleist</a></li>')
    a('                        <li><a href="#">Ping</a></li>')
    a('                        <li><a href="#">FootJoy</a></li>')
    a('                    </ul>')
    a('                </div>')
    a('                <div class="footer-newsletter">')
    a('                    <h4>Contact Us on WhatsApp</h4>')
    a('                    <p>Scan the QR code or tap to chat</p>')
    a('                    <a href="https://wa.me/8613262570197" target="_blank" style="display:inline-block;">')
    a('                        <img src="/images/whatsapp-qr.png" alt="WhatsApp" style="width:100px;height:100px;border-radius:12px;">')
    a('                    </a>')
    a('                    <p style="margin-top:8px;font-size:12px;color:rgba(255,255,255,0.7);">+86 13262570197</p>')
    a('                </div>')
    a('            </div>')
    a('            <div class="footer-bottom">')
    a('                <p>&copy; 2026 Karibu. All rights reserved.</p>')
    a('            </div>')
    a('        </div>')
    a('    </footer>')
    a('')
    a('    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>')
    a('    <script src="/script.js"></script>')
    a('    <script>AOS.init({ duration: 800, once: true });</script>')
    a('    <script>')
    a("        var lightboxImages = [];")
    a("        var currentIndex = 0;")
    a("        var lightbox = document.getElementById('lightbox');")
    a("        var lightboxImg = document.getElementById('lightboxImg');")
    a('')
    a("        function openLightbox(index) {")
    a("            currentIndex = index;")
    a("            lightboxImg.src = lightboxImages[currentIndex];")
    a("            lightbox.classList.add('active');")
    a("            document.body.style.overflow = 'hidden';")
    a("        }")
    a('')
    a("        function closeLightbox(e) {")
    a("            if (e.target === lightbox || e.target.className === 'lightbox-close') {")
    a("                lightbox.classList.remove('active');")
    a("                document.body.style.overflow = '';")
    a("            }")
    a("        }")
    a('')
    a("        function prevImage(e) { e.stopPropagation(); currentIndex = (currentIndex - 1 + lightboxImages.length) % lightboxImages.length; lightboxImg.src = lightboxImages[currentIndex]; }")
    a("        function nextImage(e) { e.stopPropagation(); currentIndex = (currentIndex + 1) % lightboxImages.length; lightboxImg.src = lightboxImages[currentIndex]; }")
    a('')
    a("        document.addEventListener('DOMContentLoaded', function() {")
    a("            var thumbs = document.querySelectorAll('.pthumb');")
    a("            thumbs.forEach(function(img, i) {")
    a("                lightboxImages.push(img.src);")
    a("                img.style.cursor = 'pointer';")
    a("                img.addEventListener('click', function(e) {")
    a("                    e.stopPropagation();")
    a("                    document.getElementById('pmain').src = this.src;")
    a("                    openLightbox(i);")
    a("                });")
    a("            });")
    a("            var mainImg = document.getElementById('pmain');")
    a("            if (mainImg) {")
    a("                if (lightboxImages.indexOf(mainImg.src) === -1) {")
    a("                    lightboxImages.unshift(mainImg.src);")
    a("                }")
    a("                mainImg.style.cursor = 'pointer';")
    a("                mainImg.addEventListener('click', function(e) {")
    a("                    var idx = lightboxImages.indexOf(this.src);")
    a("                    if (idx === -1) { idx = 0; }")
    a("                    openLightbox(idx);")
    a("                });")
    a("            }")
    a("        });")
    a('    </script>')
    a('</body>')
    a('</html>')
    
    page = '\n'.join(lines)
    
    with open(fpath, 'w', encoding='utf-8') as f:
        f.write(page)
    
    broken = len(re.findall(r'(?<!<)/div>', page)) + len(re.findall(r'^\s*<\s*$', page, re.MULTILINE))
    return len(page), len(lines), broken

for sku in SKUS:
    sz, lines, broken = write_page(sku)
    status = 'OK' if broken == 0 else f'WARN(broken={broken})'
    print(f'  {status} {sku}: {lines} lines, {sz} bytes')
