// Test real sales handlers in an isolated, persistent local preview.
// Never modifies the user's preview data, Google Sheets or Netlify.
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright-core";
import { salesFigures } from "../public/admin/sales-report.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const evidence = path.join(root, ".tmp/admin-sales-qa", String(Date.now()));
await mkdir(evidence, { recursive: true });
const dataFile = path.join(evidence, "data.json");
const child = spawn(process.execPath, [path.join(root, "execution/serve_admin_local.mjs"), "0", dataFile], { cwd: root, stdio: ["ignore", "pipe", "pipe"] });
let browser;
let serverOutput = "";
child.stderr.on("data", (chunk) => { serverOutput += chunk; });
try {
  const base = await new Promise((resolve, reject) => {
    let output = "";
    const timer = setTimeout(() => reject(new Error(`Local sales QA did not start: ${output}`)), 20_000);
    child.stdout.on("data", (chunk) => {
      output += chunk;
      const match = output.match(/Local admin: (http:\/\/127\.0\.0\.1:\d+)/);
      if (match) { clearTimeout(timer); resolve(match[1]); }
    });
    child.stderr.on("data", (chunk) => { output += chunk; });
    child.once("error", (error) => { clearTimeout(timer); reject(error); });
    child.once("exit", (code) => { clearTimeout(timer); reject(new Error(`Local QA server exited (${code}): ${output}`)); });
  });
  assert.equal((await fetch(`${base}/api/admin-sales`)).status, 401);
  const session = await fetch(`${base}/api/admin-auth`);
  const cookie = session.headers.get("set-cookie").split(";")[0];
  const api = async (route, method = "GET", body, status = 200) => {
    const response = await fetch(`${base}/api/${route}`, { method, headers: { cookie, "content-type": "application/json" }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
    assert.equal(response.status, status, await response.clone().text());
    return response.json();
  };
  assert.deepEqual((await api("admin-sales")).sales, []);
  assert(!("Sales" in JSON.parse(await readFile(dataFile, "utf8"))));
  const product = (await api("admin-products")).products[0];
  const client = (await api("admin-clients", "POST", { firstName: "QA", lastName: "Buyer" }, 201)).client;
  const today = new Date();
  const dateText = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
  const first = { id: crypto.randomUUID(), date: dateText(today), productSku: product.sku, productName: product.name, clientId: client.id, customerName: "QA Buyer", quantity: 2, unitPriceKes: "25000.75", notes: '<img src=x onerror="alert(1)">', status: "completed", totalKes: 1 };
  for (const invalid of [{ ...first, quantity: 1.5 }, { ...first, unitPriceKes: 0 }, { ...first, unitPriceKes: -1 }, { ...first, unitPriceKes: "1.001" }, { ...first, quantity: [] }, { ...first, date: "2026-02-30" }, { ...first, productName: "" }, { ...first, status: "unknown" }]) await api("admin-sales", "POST", invalid, 400);
  await api("admin-sales", "DELETE", undefined, 405);
  await api("admin-sales", "PUT", first, 404);
  const saved = (await api("admin-sales", "POST", first, 201)).sale;
  assert.equal(saved.totalKes, 50001.5);
  await api("admin-sales", "POST", first, 201);
  assert.equal((await api("admin-sales")).sales.length, 1, "A retried save must not double-count revenue");
  await api("admin-sales", "POST", { ...first, unitPriceKes: 30000 }, 409);
  const second = { ...first, id: crypto.randomUUID(), date: dateText(new Date(today.getFullYear(), today.getMonth() - 1, 15)), productSku: "", productName: "Previous club", clientId: "", customerName: "Walk-in", quantity: 1, unitPriceKes: "100", notes: "Older sale" };
  await api("admin-sales", "POST", second, 201);
  await api("admin-sales", "POST", { ...first, id: crypto.randomUUID(), status: "void", unitPriceKes: "45000" }, 201);
  const figures = salesFigures((await api("admin-sales")).sales, today);
  assert.equal(figures.totalKes, 50101.5);
  assert.equal(figures.count, 2);
  assert.equal(figures.units, 3);
  assert.equal(figures.averageKes, 25050.75);
  assert.equal(figures.months[5].totalKes, 50001.5);
  assert.equal(figures.months[4].totalKes, 100);
  assert.equal(figures.topProducts[0].totalKes, 50001.5);

  browser = await chromium.launch({ headless: true, executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe" });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  await context.route("**/*", (route) => new URL(route.request().url()).hostname === "127.0.0.1" ? route.continue() : route.abort());
  const page = await context.newPage();
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto(`${base}/admin/#sales`);
  await page.locator("#sales-count").filter({ hasText: "2" }).waitFor();
  assert.equal(await page.locator("#sales-revenue").textContent(), "KSh 50,101.50");
  assert.equal(await page.locator("#sales-units").textContent(), "3");
  assert.equal(await page.locator("#sales-average").textContent(), "KSh 25,050.75");
  assert.equal(await page.locator("#sales-rows img").count(), 0);
  await page.screenshot({ path: path.join(evidence, "desktop.png"), fullPage: true });
  await page.locator("#nav-dashboard").click();
  assert.equal(await page.locator("#dash-sales-total").textContent(), "KSh 50,101.50");
  assert.equal(await page.locator("#dash-sales-month").textContent(), "KSh 50,001.50");
  assert.equal(await page.locator("#dash-sales-month-count").textContent(), "1 sale this month");
  assert.equal(await page.locator("#dashboard-sales [data-dashboard-sale]").count(), 3);
  await page.screenshot({ path: path.join(evidence, "dashboard.png"), fullPage: true });
  await page.locator("#dashboard-sales [data-dashboard-sale]").first().click();
  await page.locator("#sale-editor").waitFor({ state: "visible" });
  await page.locator("#cancel-sale-editor").click();
  await page.locator(".sales-overview-card").first().click();
  assert.equal(await page.locator("#view-title").textContent(), "Sales");
  await page.locator("#sales-period").selectOption("month");
  assert.equal(await page.locator("#sales-revenue").textContent(), "KSh 50,001.50");
  await page.locator("#sales-period").selectOption("last-month");
  assert.equal(await page.locator("#sales-revenue").textContent(), "KSh 100");
  await page.locator("#sales-period").selectOption("all");
  await page.locator("#sales-search").fill("Previous club");
  assert.equal(await page.locator("#sales-count").textContent(), "1");
  await page.locator("#sales-search").fill("");
  await page.locator(`[data-sale-edit="${first.id}"]`).click();
  await page.locator('#sale-form [name="unitPriceKes"]').fill("75000.25");
  await page.locator('#sale-form [name="quantity"]').fill("1");
  assert.equal(await page.locator("#sale-total-preview").textContent(), "KSh 75,000.25");
  await page.locator("#save-sale").click();
  await page.locator("#sale-editor").waitFor({ state: "hidden" });
  assert.equal(await page.locator("#sales-revenue").textContent(), "KSh 75,100.25");
  await page.reload();
  await page.locator("#sales-revenue").filter({ hasText: "75,100.25" }).waitFor();
  const disk = JSON.parse(await readFile(dataFile, "utf8"));
  assert.equal(disk.Sales.length, 4, "Editing must preserve one row per sale");
  assert.equal(disk.Sales[1][8], 75000.25);
  assert.equal(disk.Sales[1][11], saved.createdAt);
  await page.locator(`[data-sale-edit="${first.id}"]`).click();
  await page.locator('#sale-form [name="status"]').selectOption("void");
  await page.locator("#save-sale").click();
  await page.locator("#sale-editor").waitFor({ state: "hidden" });
  assert.equal(await page.locator("#sales-revenue").textContent(), "KSh 100");
  await page.locator("#sales-status").selectOption("all");
  assert.equal(await page.locator("#sales-rows [data-sale-edit]").count(), 3);
  assert.equal(await page.locator("#sales-revenue").textContent(), "KSh 100");
  await page.locator("#nav-clients").click();
  await page.locator("[data-client-sale]").click();
  assert.equal(await page.locator("#sale-client").inputValue(), client.id);
  assert.equal(await page.locator('#sale-form [name="customerName"]').inputValue(), "QA Buyer");
  await page.locator("#sale-product").selectOption(product.sku);
  assert.equal(await page.locator('#sale-form [name="productName"]').inputValue(), product.name);
  assert.equal(await page.locator('#sale-form [name="unitPriceKes"]').inputValue(), "");
  await page.locator("#cancel-sale-editor").click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('.mobile-admin-nav [data-go="dashboard"]').click();
  assert(await page.locator("#dash-sales-total").isVisible());
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.locator('.mobile-admin-nav [data-go="sales"]').click();
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.locator("#new-sale").click();
  assert(await page.locator("#save-sale").evaluate((button) => button.getBoundingClientRect().bottom <= innerHeight));
  assert(await page.evaluate(() => document.querySelector("#sale-editor").scrollWidth <= document.querySelector("#sale-editor").clientWidth));
  await page.screenshot({ path: path.join(evidence, "mobile-form.png"), fullPage: true });
  assert.deepEqual(errors, []);
  const report = { validation: "passed", actualPricesAndTotals: "passed", dashboardSales: "passed", retryWithoutDuplication: "passed", editReloadAndPersistence: "passed", voidExclusion: "passed", periodFilters: "passed", clientAndProductSelection: "passed", mobile: "passed", userPreviewWrites: 0, cloudRequests: 0 };
  await writeFile(path.join(evidence, "report.json"), JSON.stringify(report, null, 2));
  console.log(JSON.stringify({ ...report, evidence }, null, 2));
} catch (error) { console.error(serverOutput); throw error; }
finally {
  await browser?.close();
  if (child.exitCode === null && child.signalCode === null) await new Promise((resolve) => { child.once("close", resolve); child.kill(); });
}
